
// Generated field mappings for database migration
export const DATABASE_FIELD_MAPPINGS = {
  "attendeeId": "attendee_id",
  "createdAt": "created_at",
  "eventId": "event_id",
  "addressLine1": "address_line1",
  "addressLine2": "address_line2",
  "billingCity": "billing_city",
  "billingCountry": "billing_country",
  "billingEmail": "billing_email",
  "billingFirstName": "billing_first_name",
  "billingLastName": "billing_last_name",
  "billingOrganisationName": "billing_organisation_name",
  "billingPhone": "billing_phone",
  "billingPostalCode": "billing_postal_code",
  "billingState": "billing_state",
  "billingStreetAddress": "billing_street_address",
  "businessName": "business_name",
  "contactId": "contact_id",
  "firstName": "first_name",
  "lastName": "last_name",
  "organisationId": "organisation_id",
  "postalCode": "postal_code",
  "stripeCustomerId": "stripe_customer_id",
  "updatedAt": "updated_at",
  "userId": "user_id",
  "eventTicketId": "event_ticket_id",
  "packageId": "package_id",
  "availableCount": "available_count",
  "eventUuid": "event_uuid",
  "reservedCount": "reserved_count",
  "soldCount": "sold_count",
  "ticketDefinitionId": "ticket_definition_id",
  "totalCapacity": "total_capacity",
  "displayScopeId": "display_scope_id",
  "eventEnd": "event_end",
  "eventIncludes": "event_includes",
  "eventStart": "event_start",
  "imageUrl": "image_url",
  "importantInformation": "important_information",
  "isMultiDay": "is_multi_day",
  "isPurchasableIndividually": "is_purchasable_individually",
  "maxAttendees": "max_attendees",
  "parentEventId": "parent_event_id",
  "registrationAvailabilityId": "registration_availability_id",
  "agreeToTerms": "agree_to_terms",
  "customerId": "customer_id",
  "paymentStatus": "payment_status",
  "primaryAttendeeId": "primary_attendee_id",
  "registrationData": "registration_data",
  "registrationDate": "registration_date",
  "registrationId": "registration_id",
  "registrationType": "registration_type",
  "stripePaymentIntentId": "stripe_payment_intent_id",
  "totalAmountPaid": "total_amount_paid",
  "totalPricePaid": "total_price_paid",
  "originalPrice": "original_price",
  "purchasedAt": "purchased_at",
  "reservationExpiresAt": "reservation_expires_at",
  "reservationId": "reservation_id"
};

export const DATABASE_TABLE_MAPPINGS = {
  "AttendeeEvents": "attendeeevents",
  "Attendees": "attendees",
  "Customers": "customers",
  "DisplayScopes": "displayscopes",
  "EventPackageTickets": "eventpackagetickets",
  "EventPackages": "eventpackages",
  "EventTickets": "eventtickets",
  "Events": "events",
  "MasonicProfiles": "masonicprofiles",
  "OrganisationMemberships": "organisationmemberships",
  "Registrations": "registrations",
  "Tickets": "tickets"
};

export const DATABASE_ENUM_MAPPINGS = {
  "Directly": "directly",
  "Guest": "guest",
  "Mason": "mason",
  "PrimaryAttendee": "primaryattendee",
  "ProvideLater": "providelater",
  "GuestPartner": "guestpartner",
  "LadyPartner": "ladypartner",
  "Company": "company",
  "GrandLodge": "grandlodge",
  "Lodge": "lodge",
  "MasonicOrder": "masonicorder",
  "Other": "other",
  "Groups": "groups",
  "Individuals": "individuals",
  "Officials": "officials"
};
