create view public.contacts_view as
select
  c.contact_id,
  c.auth_user_id,
  c.title,
  c.first_name,
  c.last_name,
  c.suffix_1,
  c.suffix_2,
  c.suffix_3,
  c.email,
  c.mobile_number,
  c.address_line_1,
  c.address_line_2,
  c.suburb_city,
  c.state,
  c.country,
  c.postcode,
  c.dietary_requirements,
  c.special_needs,
  c.type,
  c.has_partner,
  c.is_partner,
  c.organisation_id,
  c.business_name,
  c.billing_organisation_name,
  c.billing_email,
  c.billing_phone,
  c.stripe_customer_id,
  c.source_type,
  c.created_at,
  c.updated_at,
  mp.masonic_title,
  mp.rank,
  mp.grand_rank,
  mp.grand_officer,
  mp.grand_office,
  mp.lodge_id,
  mp.grand_lodge_id,
  array_agg(distinct om.organisation_id) filter (
    where
      om.organisation_id is not null
  ) as member_of_organisations,
  array_agg(distinct om.role_in_org) filter (
    where
      om.role_in_org is not null
  ) as organisation_roles
from
  contacts c
  left join masonic_profiles mp on c.contact_id = mp.contact_id
  left join organisationmemberships om on c.contact_id = om.contact_id
group by
  c.contact_id,
  c.auth_user_id,
  c.title,
  c.first_name,
  c.last_name,
  c.suffix_1,
  c.suffix_2,
  c.suffix_3,
  c.email,
  c.mobile_number,
  c.address_line_1,
  c.address_line_2,
  c.suburb_city,
  c.state,
  c.country,
  c.postcode,
  c.dietary_requirements,
  c.special_needs,
  c.type,
  c.has_partner,
  c.is_partner,
  c.organisation_id,
  c.business_name,
  c.billing_organisation_name,
  c.billing_email,
  c.billing_phone,
  c.stripe_customer_id,
  c.source_type,
  c.created_at,
  c.updated_at,
  mp.masonic_title,
  mp.rank,
  mp.grand_rank,
  mp.grand_officer,
  mp.grand_office,
  mp.lodge_id,
  mp.grand_lodge_id;