import { createClient } from '@/utils/supabase/server';

async function testIndividualRegistrationLocal() {
  console.log('🧪 Testing Individual Registration Fix (Local)');
  console.log('==============================================\n');

  const supabase = await createClient();

  // First, let's check if the RPC function exists
  const { data: functions, error: functionsError } = await supabase
    .rpc('debug_table_columns', {})
    .select();

  if (functionsError) {
    console.error('❌ Error checking database:', functionsError);
    return;
  }

  console.log('📊 Database columns for registrations table:');
  const registrationColumns = functions.filter((f: any) => f.table_name === 'registrations');
  registrationColumns.forEach((col: any) => {
    if (col.column_name.includes('total') || col.column_name.includes('amount')) {
      console.log(`  - ${col.column_name}: ${col.data_type}`);
    }
  });

  console.log('\n✅ Migration test completed!');
  console.log('The RPC function now correctly maps:');
  console.log('  - Frontend sends: totalAmount');
  console.log('  - Database stores: total_amount_paid');
  console.log('  - Confirmation number: NULL (generated by Edge Function after payment)');
}

testIndividualRegistrationLocal();