-- Update catalog object IDs for packages to match Square sandbox
-- This updates the catalog_object_id column to use the actual IDs generated by Square

-- Update Lodge Package
UPDATE packages 
SET catalog_object_id = 'OVYH3JSFOI2GSSDR3XV6SKQB'
WHERE package_name = 'Lodge Package' 
  AND package_description LIKE '%Package for Lodges%';

-- Update Individual Ticket (if exists)
UPDATE packages 
SET catalog_object_id = '4COQMBSQ2TNAGFUPG5XVCRUG'
WHERE package_name = 'Individual Ticket'
  OR package_name LIKE '%Individual%';

-- Update Delegation Package (if exists)
UPDATE packages 
SET catalog_object_id = 'CPWTGL6KY3ZLQ5PPXVBUX4LI'
WHERE package_name = 'Delegation Package'
  OR package_name LIKE '%Delegation%';

-- Show the updated packages
SELECT package_id, package_name, catalog_object_id, package_price
FROM packages
WHERE function_id = 'eebddef5-6833-43e3-8d32-700508b1c089';