create table public."Events" (
  title text not null,
  location text null,
  description text null,
  type text null,
  "isPurchasableIndividually" boolean null default true,
  "maxAttendees" bigint null,
  featured boolean null default false,
  "imageUrl" text null,
  "eventIncludes" text[] null,
  "importantInformation" text[] null,
  latitude numeric null,
  longitude numeric null,
  "createdAt" timestamp with time zone not null default now(),
  "isMultiDay" boolean null default false,
  id uuid not null default gen_random_uuid (),
  "parentEventId" uuid null,
  "registrationAvailabilityId" uuid null,
  "displayScopeId" uuid null,
  slug text not null,
  "eventStart" timestamp with time zone null,
  "eventEnd" timestamp with time zone null,
  locationid uuid null,
  organiserorganisationid uuid null,
  price numeric null,
  "eventId" text null default ''::text,
  subtitle text null,
  organizer_name text null,
  organizer_contact jsonb null,
  is_published boolean null default true,
  publish_option text null,
  regalia text null,
  regalia_description text null,
  dress_code text null,
  degree_type text null,
  sections jsonb null,
  attendance jsonb null,
  documents jsonb null,
  related_events uuid[] null,
  location_json jsonb null,
  organiser_logo text null,
  constraint events_pkey primary key (id),
  constraint events_id_uuid_unique unique (id),
  constraint Events_eventId_key unique ("eventId"),
  constraint events_slug_key unique (slug),
  constraint events_organiserorganisationid_fkey foreign KEY (organiserorganisationid) references organisations (organisationid) on delete set null,
  constraint events_parent_event_id_fkey foreign KEY ("parentEventId") references "Events" (id) on delete RESTRICT,
  constraint events_display_scope_id_fkey foreign KEY ("displayScopeId") references "DisplayScopes" (id),
  constraint events_registration_availability_id_fkey foreign KEY ("registrationAvailabilityId") references registration_availabilities (id),
  constraint events_locationid_fkey foreign KEY (locationid) references locations (locationid) on delete set null
) TABLESPACE pg_default;